### ISSUE TITLE
Can you please demonstrate how to define env variables in _config.

### ISSUE THREAD

**Issue by sharu725** [iBug/jekyll-environment-variables#1]
A little more elaboration would be great.
Thank you

**Comment by iBug** [comment]
You don't define environment variables in `_config.yml`, but rather install this gem and use them directly. It's a very simple plugin and the usage is demonstrated clear enough in [README](https://github.com/iBug/jekyll-environment-variables/blob/master/README.md).

**Comment by sharu725** [comment]
> You don't define environment variables in `_config.yml`, but rather install this gem and use them directly. It's a very simple plugin and the usage is demonstrated clear enough in [README](https://github.com/iBug/jekyll-environment-variables/blob/master/README.md).

I would like to know how to use if after installing this gen.

You have mentioned

```
Hostname: {{ site.env.HOSTNAME }}
My home: {{ site.env.HOME }}
```

What are these? 

Also,

> All environment variables will be copied to site.env for use in Liquid templates.

What does this mean? Where are environment variables?

Let's say, I want an API key XYZ for development and ABC for Prodcution, how do I do it using your gem?

**Comment by iBug** [comment]
This is the point:

> All environment variables will be copied to `site.env` **for use in Liquid templates**.

Let's say for example, when you build your site on Travis CI, where you have `TRAVIS_BUILD_NUMBER` in environment, then you can show it in your site with the following Markdown or HTML:

```
This site is built from Travis CI build {{ site.env.TRAVIS_BUILD_NUMBER }}
```

As a live example, you can view [the status page](https://ibugone.com/status) of my website where I use similar environment variables from CircleCI. ([source](https://github.com/iBug/iBug-source/blob/b09a38d09d28d1e22d403ac0cbc1063e820dc90e/_home/status.html#L27))

To clarify, this gem is only intended to enable you to render environment variables into generated HTML, and not other parts of the website (like `_config.yml`). If you're looking to utilize your API keys, you probably need a custom build script ([example](https://github.com/Charcoal-SE/charcoal-se.github.io/blob/de045a6336a4d6ac15e1a0f4fc99a260c8026b58/script/build#L93)) rather than this gem.

**Comment by sharu725** [comment]
Thank you @iBug . That helped.
